theme: jekyll-theme-slate
name: Messa per Nonno Giuseppe
title: Messa per Nonno Giuseppe
title_prefix: 'Messa'
tag_title_prefix: 'Messa'
github:
  is_project_page: false
header:
  image: /assets/images/MVIMG_20200701_220450.jpg
